### ISSUE TITLE
Allow specifying full namespace as a `--namespace` value

### ISSUE THREAD

**Issue by rabraghib** [zenstruck/foundry#169]
it would be good if we are able to specifying the full namespace (`App\..` or `App\Tests\...`) since Its standard for namespaces and its always the first way anyone will try to use the `--namespace` flag with
& also if we can set its default value in the config
```yml
zenstruck_foundry:
    default:
        namespace: App\Factory
```
