### ISSUE TITLE
Add support to PHP8 Attributes

### ISSUE THREAD

**Issue by taboritis** [zenstruck/foundry#201]
Please, add compatibility with PHP8 Attributes

``` yaml
doctrine:
    orm:
        mappings:
            App:
                type: attribute
```
