### ISSUE TITLE
Instantiator always force properties configuration seems not to work as expected

### ISSUE THREAD

**Issue by flohw** [zenstruck/foundry#261]
Hi again :-)

I am changing the way I use factories and fixtures in my tests to use it as suggested here : https://github.com/zenstruck/foundry/issues/256#issuecomment-1040478519

So I configured the bundle like this:
```yaml
# config/packages/dev/zenstruck_foundry.yaml
zenstruck_foundry:
    auto_refresh_proxies: true
    instantiator:
        without_constructor: true
        always_force_properties: true
    faker:
        locale: fr_FR # set the locale
```

Removed my `initialize` methods and set a `getDefaults` to map my properties to values I want:
```php
    protected function getDefaults(): array
    {
        return [
            'published' => 'true',
            'name' => 'Marché',
            'incentivable' => false,
            'createdAt' => new \DateTimeImmutable('today'),
            'updatedAt' => new \DateTimeImmutable('today'),
            'path' => 'Marché',
            'parent' => null,
        ];
    }
```

Now, when I create use the factory: `$category = CategoryFactory::new()->create()->object();` I get the error `Could not determine access type for property "path" in class "App\Domain\Entity\Referential\Category".` as my property `path` is computed from the entity, I removed the setter. But the configuration looks to not be used because debugging here [`src/Instantiator.php:46`](https://github.com/zenstruck/foundry/blob/71f08af3d9b9e98d5c67848ff7330467f3373dad/src/Instantiator.php#L46) the `alwaysForceProperties` is false.

But as soon as I create the `initialize` method in my factory with `return $this->instantiateWith((new Instantiator())->alwaysForceProperties());` it works as expected.

Maybe the configuration is lost somewhere, but I don't know where. Or maybe I miss a configuration again or a small thing I didn't find yet?

I hope I gave enough details about the issue to reproduce if needed :slightly_smiling_face: 

EDIT: After some other tweeks and removing some useless code (at least I thought it was useless) the issue applies to `without_constructor` global configuration too :confused:
