### ISSUE TITLE
[Feature Request] Allow to pass index in `createMany()` callback

### ISSUE THREAD

**Issue by Kocal** [zenstruck/foundry#316]
Hi! 

I'm currently migrating. from Alice (and AliceBundle) to Foundry, but I lack from an interesting feature, the [fixtures list](https://github.com/nelmio/alice/blob/master/doc/complete-reference.md#fixture-lists).

With Alice, the following code will generate 6 users with username `front_user1`, `front_user2`, etc...: 
```yaml
App\Core\Entity\User\User:
    forum_user_{1..6}:
        username: 'front_user<current()>'
        email: 'front_user<current()>\@foobar.com'
```

However I don't find the equivalent with Foundry, I was hoping to use `createMany` but it does not work as I expected: 
```php
UserFactory::createMany(6, function (int $number) {
    return [
        'username' => 'front_user' . $number,
        'email' => 'front_user' . $number . '@foobar.com',
    ];
});
```

It seems the current workaround is: 
```php
for ($i = 1; $i <= 6; ++$i) {
    UserFactory::createOne([
        'username' => 'front_user' . $i,
        'email' => 'front_user' . $i . '@foobar.com',
    ]);
}
```

It's not really a big deal, and maybe it was on purpose when developing Foundry, but WDYT about it?

Thanks
