### ISSUE TITLE
Remove "bundleless" usage

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#319]
Based on #110 and https://github.com/zenstruck/foundry/issues/311#issuecomment-1275669557 we would like to remove "bundleless" usage.

Here are some thoughts:
- [x] all env vars such as `FOUNDRY_RESET_CONNECTIONS` or `FOUNDRY_RESET_OBJECT_MANAGERS` should be passed as config https://github.com/zenstruck/foundry/pull/320
- [x] add something like `FOUNDRY_RESET_ODM_OBJECT_MANAGERS` https://github.com/zenstruck/foundry/pull/320
- [ ] "bundleless" usage should not require doctrine (there is presently an error when requiring foundry without doctrine) - the factories would automatically be with `withoutPersisting()`  behavior
- [x] we could deprecate using TestState with KernelTestCase - triggered if the bundle isn't enabled. Then we could say "TestState is only applicable to non-Kernel (unit) tests" https://github.com/zenstruck/foundry/pull/322

**Comment by kbond** [comment]
> we need to keep the ability to add global state in

We do but I wonder if this could be configured?

```yaml
zenstruck_foundry:
    global_state:
        - invokable.service # just a service with ::invoke()
        - App\Stories\StoryThatIsAService
        - App\Stories\GlobalStory # if not a service, just run GlobalStory::load()
        - ...
```

Then global state could be used in your dev environment when loading fixtures. Stories as services could now be used as global state too.

If this can be done, maybe we can deprecate `TestState::addGlobalState()` too.
