### ISSUE TITLE
ci: Lint documentation

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#446]
https://github.com/OskarStark/doctor-rst

**Comment by cezarpopa** [comment]
Hi Kevin,

I hope all is well, I was wondering whether this is still relevant for the project? I have already configured the linter and initial rules and could draft a PR for it.

One point I am particularly unsure about is the initial set of rules for the RST linter.

Would something like this suffice as the initial config?

```yaml
rules:
    short_array_syntax: ~
    max_blank_lines:
        max: 2
    yaml_instead_of_yml_suffix: ~
    composer_dev_option_not_at_the_end: ~
    versionadded_directive_should_have_version: ~
    unused_links: ~
    filename_uses_underscores_only: ~
```

Thank you,
Cezar
