### ISSUE TITLE
ResetDatabase does not work with multiple schemas

### ISSUE THREAD

**Issue by Qronicle** [zenstruck/foundry#495]
[Version: 1.35]

We're having issues with the `ResetDatabase` trait ever since we introduced new schemas to our PostgreSQL database. (In addition to the default "public" scheme, that is.)

After a little digging I found that the issue lies with how the database is cleared in the `ORMDatabaseResetter::dropSchema` method. The `doctrine:schema:drop` command does not seem to drop the schemas, but `doctrine:schema:create` tries to recreate them anyway in `ORMDatabaseResetter::createSchema`, which throws an exception.

I can fix it (for me) by just executing the `doctrine:schema:update` command instead, in `ORMDatabaseResetter::createSchema`. I'm pretty sure this will work for non-postgres platforms as well.

**Comment by kbond** [comment]
Hi @Qronicle, did you configure both object managers in the config?

```yaml
zenstruck_foundry:
    database_resetter:
        orm:
            object_managers:
                - default
                - other
```
