### ISSUE TITLE
make:story command can't change default namespace

### ISSUE THREAD

**Issue by dmitryuk** [zenstruck/foundry#591]
```
    zenstruck_foundry:
//...
        make_factory:
            default_namespace: 'App\DataFixtures\Factory'
```

`./bin/console make:factory`  creates files in `App\DataFixtures\Factory` correctly

But while using `./bin/console make:story` it is impossible to configure default namespace. I should set it on `symfony/maker` level, but it is unusable cause I have a lot of another `make` commands that works correctly already
