### ISSUE TITLE
Invalid service "App\Foundry\PostFactory": class "Zenstruck\Foundry\ModelFactory" not found while loading "App\Foundry\PostFactory"

### ISSUE THREAD

**Issue by norkunas** [zenstruck/foundry#593]
This already happened to me already in 2 projects.
Factories are basically set stone and not changing, maybe adding only new ones.

And just randomly with one project this started to occur on the [docker image building step](https://github.com/dunglas/symfony-docker/blob/main/Dockerfile).

In the second project with [deployer](https://deployer.org/) now I'm seeing this also on the cache:clear.

Current workaround is to move this library requirement to non-dev? I've defined on all factories `#[When('dev')]` and `#[When('test')]` and don't use them in production code.. So I don't understand why it fails, or this is something that should be fixed in Symfony?

**Comment by dmitryuk** [comment]
The library must be within `dev` composer section.
>>I've defined on all factories #[When('dev')] and #[When('test')] and don't use them in production code

I think you called `cache:clear` in dev environment, but `compose install` was with `--no-dev`
Try `APP_ENV=production composer install`

**Comment by norkunas** [comment]
```
#30 [frankenphp_prod 8/8] RUN set -eux; 	mkdir -p var/cache var/log var/storage; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer dump-env prod; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync;
#30 0.061 + mkdir -p var/cache var/log var/storage
#30 0.062 + composer dump-autoload --classmap-authoritative --no-dev
#30 0.225 Generating optimized autoload files (authoritative)
#30 9.151 Generated optimized autoload files (authoritative) containing 19049 classes
#30 9.164 + composer dump-env prod
#30 9.375 Successfully dumped .env files in .env.local.php
#30 9.382 + composer run-script --no-dev post-install-cmd
#30 9.549 
#30 9.549 Run composer recipes at any time to see the status of your Symfony recipes.
#30 9.549 
#30 9.555 Executing script cache:clear [KO]
#30 10.02  [KO]
#30 10.02 Script cache:clear returned with error code 1
#30 10.02 !!  
#30 10.02 !!  In AbstractRecursivePass.php line 177:
#30 10.02 !!                                                                                 
#30 10.02 !!    Invalid service "App\Foundry\PostFactory": class "Zenstru  
#30 10.02 !!    ck\Foundry\ModelFactory" not found while loading "App\Foundry\Factory\PostFactory".                                                           
```

I think it runs with prod env, because in [dunglas/symfony-docker](https://github.com/dunglas/symfony-docker/blob/main/Dockerfile) there is `ENV APP_ENV=prod` set above the failed instructions

**Comment by dmitryuk** [comment]
can you send your services.yaml ?

**Comment by norkunas** [comment]
```
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Security/SecurityIdentity.php'

    app.redis:
        class: Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments: ['%env(REDIS_DSN)%']

when@prod:
    parameters:
        .container.dumper.inline_factories: true
```
