### ISSUE TITLE
Memory leak during PHPunit test with the ResetDatabase

### ISSUE THREAD

**Issue by svianney** [zenstruck/foundry#678]
| Package | Version |
|--------|--------|
| Symfony | 7.1 |
| Foundry | 2.0.7 |
| PHPunit | 10.5.28 |

Hi, 

I've been recently confronted to a memory leak when executing my PHPunit tests. After investigations, I might have found that it is caused by the `ResetDatabase` trait. 

I've not found what might cause this in the trait yet, I'm still investigating. 

You can reproduce the problem with a simple test case like below.

```
<?php

namespace App\Tests;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

#[Group('memory')]
class MemoryLeakTest extends KernelTestCase
{
    public static function data(): \Generator
    {
        for ($i = 0; $i < 10; $i++) {
            yield [];
        }
    }

    #[DataProvider('data')]
    public function testMemoryUsage(): void
    {
        echo sprintf("%s MB",number_format(memory_get_usage()/1000000, 0)) . PHP_EOL;
        $this->assertTrue(true);
    }
}

```

With this test I get results like this:
<img width="580" alt="image" src="https://github.com/user-attachments/assets/d97f05f0-2bf9-4ab9-a452-b29715dd549d">

When I add the ResetDatabase trait like this:
```
<?php

namespace App\Tests;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Test\ResetDatabase;

#[Group('memory')]
class MemoryLeakTest extends KernelTestCase
{
    use ResetDatabase;

    public static function data(): \Generator
    {
        for ($i = 0; $i < 10; $i++) {
            yield [];
        }
    }

    #[DataProvider('data')]
    public function testMemoryUsage(): void
    {
        echo sprintf("%s MB",number_format(memory_get_usage()/1000000, 0)) . PHP_EOL;
        $this->assertTrue(true);
    }
}

```

Results are:
<img width="580" alt="image" src="https://github.com/user-attachments/assets/aca39342-0598-4b4d-9c8c-cdee2613a074">

I will be happy to make a PR if I find out how to solve this. 
Thanks for your time.

**Comment by nikophil** [comment]
Hi @svianney 

Maybe this could come from the global state, do you have any configured?

**Comment by svianney** [comment]
Thanks @nikophil for your answer but I'm not sure what you mean, if I have any global state configured, it would be without knowing what I'm doing then. See my simple phpunit.xml.dist below if it helps.

```
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
>
    <php>
        <ini name="display_errors" value="1" />
        <ini name="error_reporting" value="-1" />
        <ini name="memory_limit" value="-1" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="10.5" />
        <server name="SYMFONY_DEPRECATIONS_HELPER" value="max[self]=0&amp;max[direct]=0&amp;quiet[]=indirect&amp;quiet[]=other"/>
    </php>

    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <extensions>
        <bootstrap class="App\Tests\PHPUnit\BypassFinalsExtension"></bootstrap>
    </extensions>
</phpunit>

```

I've tried to remove my custom extension in order to check that it was not interfering and the results are the same as presented above. 

If you want me to provide more information, let me know.

**Comment by nikophil** [comment]
global state is a Foundry feature: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#global-state

I'm _suspect_ that the culprit is not Foundry here, because when I'm doing the same thing in one of my app, the memory consumption does not grow...
 
Could you try to add a `self::bootKernel()` inside you `testMemoryUsage()` when NOT using `ResetDatabase` and see if the memory leak occurs?

**Comment by svianney** [comment]
Thanks for the clarification, I have no global state configured. see my configuration:
```
when@dev: &dev
    zenstruck_foundry:
        auto_refresh_proxies: true

when@test: *dev
```

I tried to add `self::bootKernel()`, it augmented the memory usage from 10MB to 27MB right from the first test but doesn't grow.

<img width="334" alt="image" src="https://github.com/user-attachments/assets/6fb377d3-8424-4880-a234-21aae5847150">

**Comment by svianney** [comment]
I remember my project have one particularity though. 
I configured 3 mappings on one doctrine connection. I'm not telling this is the cause but I think this could be an important information to know. 

```
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Wazo:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Bridge/Wazo/Entity'
                prefix: 'App\Bridge\Wazo\Entity'
                alias: Wazo
            Bridge:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Bridge/Entity'
                prefix: 'App\Bridge\Entity'
                alias: Bridge
```

Edit: And also have this kind of inheritance:

```
#[ORM\Entity]
#[ORM\InheritanceType('JOINED')]
abstract class Node
```

I will try to test on a fresh new project.

Edit2:
I have deleted everything in my project and the memory leak seems to be not present anymore. The memory goes from 57 to 59 up and down without growing. 
So it seems that something in my configuration is not compatible. 
I'll try to dig around the 2 previous information I provided to find what's wrong: 
- The inheritance
- The multiple mappings
I'll comment if I found anything.

Until then, I think we can close this issue as it is not yet proven to be related to this bundle. 

Thanks for your time.
