### ISSUE TITLE
Default namespace adding a App\ as a prefix

### ISSUE THREAD

**Issue by ldefautubi** [zenstruck/foundry#698]
I want to use Foundry in my project to generate fixtures. I've configured the `zenstruck_foundry.yaml` as the following :
```
zenstruck_foundry:
    make_factory:
        # Default namespace where factories will be created by maker.
        default_namespace: \Tcs\Service\ServiceName\Factory
```
but when I do a `bin/console make:factory`, and choosing the entity I need,  I have this error :
```
Could not determine where to locate the new class "App\Tcs\Service\ServiceName\Factory\DeviceFactory", maybe try with a full namespace like "\My\Full\Namespace\DeviceFactory"
```
