### ISSUE TITLE
Document using custom faker providers

### ISSUE THREAD

**Issue by kbond** [zenstruck/foundry#74]
With a faker generator factory service:

```php
namespace Your\Namespace;

class FakerGenerator
{
    public static function create(): \Faker\Generator
    {
        $generator = \Faker\Factory::create();
        $generator->addProvider(new TitleProvider($generator));
        return $generator;
    }
}
```
```yaml
services:
    my_faker:
        class: Faker\Generator
        factory: ['Your\Namespace\FakerGenerator', 'create']

zenstruck_foundry:
    faker:
        service: my_faker
```

Or with a custom faker generator:

```php
namespace Your\Namespace;

use Your\Namespace\YourProvider;
use Faker\Generator;
use Faker\Factory;

class CustomGenerator extends Generator
{
    public function __construct()
    {
        // Get a default generator with default providers
        $generator = Factory::create();

        // Add custom providers
        $generator->addProvider(new YourProvider($generator));

        // copy default and custom providers to this custom generator
        foreach ($generator->getProviders() as $provider) {
            $this->addProvider($provider);
        }
    }
}
```

```yaml
zenstruck_foundry:
    faker:
        service: Your\Namespace\CustomGenerator
```
