### ISSUE TITLE
Custom database resetter

### ISSUE THREAD

**Issue by Nyholm** [zenstruck/foundry#770]
Documentation [says](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#extending-reset-mechanism) to extend `OrmResetter::class`, however, that does not work in 2.3.1. 

You need to tag your service with (the internal) tag: `.foundry.persistence.database_resetter`. 

```yaml
    services:
        App\Tests\Integration\DatabaseResetter:
            tags:
                - { name: .foundry.persistence.database_resetter, priority: -10 }
```

```php
final readonly class DatabaseResetter implements OrmResetter
{
    // ...
```
