### ISSUE TITLE
[Maker] Option to not generate the factories with the "beginner" hints

### ISSUE THREAD

**Issue by nikophil** [zenstruck/foundry#800]
All those "beginner" hints from `make:factory` pollute the factories 😅 

I think we can add a config option to disable them 😇 
```yaml
zenstruck_foundry:
     make_factory:
         display_hints: false # default is true
```
