### ISSUE TITLE
[Make] Overriding file path and template file

### ISSUE THREAD

**Issue by Hakihiro** [zenstruck/foundry#89]
Hello, thanks for your bundle,
We are currently adding foundry to our fixtures in our project, but we want to put all things in a subfolder inside `DataFixtures` folder like `DataFixtures/Story` and `DataFixtures/Factory` to group all things around ou fixtures.

Of course, we can do this without any problem but is there a way that we can override the folder destination in the make commands? I see the "test" option, but of course, this doesn't fit with our needs but it's the same spirit.

Since `MakeFactory` and `MakeStory` are `final` we can't extend them to change that. We can only copy/past it in our own command, but we will miss all of your future updates.

Maybe an option freer like `--destination` in the spirit of the test option can do the job?

And we would like to override the template because we don't need an empty instantiate function in all of our files, so if you have an idea to make that too, you're welcome.

Have a nice day guys!

**Comment by kbond** [comment]
Hello, something like this?

```bash
make:factory --namespace=DataFixtures\\Factory --template=path/to/my/Factory.tpl.php
make:story --namespace=DataFixtures\\Story --template=path/to/my/Story.tpl.php
```

**Comment by Hakihiro** [comment]
Something like this could work, it will be redundant to specify each time the folder instead of a global override, maybe this in addition with a configurable `namespace` and `template` like :

```
zenstruck_foundry:
    namespace:  DataFixtures\\Factory
    template: path/to/my/
```

Could be easier to use because in our case we will never (except for test but it's another case) be in another namespace/folder..

**Comment by kbond** [comment]
Yeah, good call, I think I'd prefer this and not add the options to the command. Maybe:

```yaml
zenstruck_foundry:
    maker:
        factory:
            namespace:  DataFixtures\\Factory
            template: path/to/my/
        story:
            namespace:  DataFixtures\\Story
            template: path/to/my/
```
